### ISSUE TITLE
test issue 

### ISSUE THREAD

**Issue by toshiakiasakura** [toshiakiasakura/rakutto_collect_project#1]
this is test issue. 
no purpose.

**Comment by toshiakiasakura** [comment]
@shunozawa    
issueのテスト。 Not watching 設定だったら届くはず。

**Comment by shunozawa** [comment]
@toshiakiasakura 
Issueテスト、しゅんバージョンです。届いてますか？

**Comment by toshiakiasakura** [comment]
@shunozawa   @tkimura1015 
jupyter lab に移行しようと昨日試してみましたが、vim が version1では使えず、　
有用なextensionsがversion2でしか動かないことが発覚したので、
僕はしばらく、jupyter notebookで作業することにしました。

良い jupyter labのextensionについては以下の3つです。
- @jupyterlab/toc
- @jupyterlab/git
- lckr/jupyterlab_variableinspector
git は特に、gitの仕組みが可視化されるのでオススメです。 

また、このrepositoryに関しては、自由に使って大丈夫です。 
僕は、しっかりとした merge に対して整理がされるまで、
_asa_ のブランチで主に作業していきます。 
push は定期的に行っていきます。

試しに色々、動かしてみるので、watching にしてると
やたらとメールが届くかもしれません。お願いします。
