### ISSUE TITLE
積極的疫学調査調査票の残りの作業。

### ISSUE THREAD

**Issue by toshiakiasakura** [toshiakiasakura/rakutto_collect_project#15]
@shunozawa 

- [x] 中間ファイルが作成されている場合があるので、その時は、そのファイルを無視するようにする。（よくあるケースは、ファイルが空いている場合。）
- [x] openpyxl でエクセルファイルが開いているか確認するコードが欲しい。
- [x] ファイルを一つに出力する。プラス、どの元データを用いたかも（ファイル名だけでよし。）違うシートに書き出す。
```
    dir_ = _utils.getOutputDir()
    pathOutput = dir_ + path.split("/")[-1][:-5] + f"_日付集計.xlsx"

    with pd.ExcelWriter(pathOutput, engine = 'openpyxl' , mode='w') as writer: 
        posi.to_excel(writer, sheet_name="ファイル"),
        occur.to_excel(writer, sheet_name="発生状況別"),

```

**Comment by shunozawa** [comment]
承知しました。頑張ります！

**Comment by shunozawa** [comment]
フォーマットの変更がありましたが、プログラムは問題なく動いてるので変更は必要ないと思われます。

**Comment by shunozawa** [comment]
時間が少しかかるのが気になりますかね。
openpyxlからpandasへの移行も検討するべきかも知れません

**Comment by toshiakiasakura** [comment]
エクセルが開いているかは、中間ファイルの存在の有無で確認。
また、objectの丸から値を抜き出すプログラムに関しては、xlwingsで対応ですね。
